#server config
server:
  port: 8888
  servlet:
    context-path: /Quick-Start-Demo


#log config
logging:
  config: classpath:log4j2.xml
  level:
    com.wusiq: info

#
#
##mybatis config
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  typeAliasesPackage: com.wusiq.repository.bean
#
## database connection configuration
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mydatabase?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: defaultAccount
#    password: defaultPassword
